{
  "All": [
    {
      "Full Name": "Bailey-Gates, Connor",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth+",
      "Phone Number": "(415) 457-4300",
      "Email Address": "connormbg@gmail.com",
      "Street 1": "97 Gregory Dr",
      "City": "Fairfax",
      "State": "CA",
      "Zip Code": "94930"
    },
    {
      "Full Name": "Barton, James",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Youth+",
      "Phone Number": "(415) 785-7899",
      "Email Address": "actorboy1234@gmail.com",
      "Street 1": "26 College Court",
      "City": "Larkspur",
      "State": "CA",
      "Zip Code": "94939"
    },
    {
      "Full Name": "Barton, Thomas",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth+",
      "Phone Number": "(415) 785-7899",
      "Email Address": "thomasbarton9@comcast.net",
      "Street 1": "26 College Court",
      "City": "Larkspur",
      "State": "CA",
      "Zip Code": "94939"
    },
    {
      "Full Name": "Bauer, Thomas",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth+",
      "Phone Number": "(415) 453-4391",
      "Email Address": "apbauer@aol.com",
      "Street 1": "114 Mission Ave",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Boris, Matthew",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Youth+",
      "Phone Number": "(415) 435-3368",
      "Email Address": "saboris@pacbell.net",
      "Street 1": "3 Apolo Rd.",
      "City": "Tiburon",
      "State": "CA",
      "Zip Code": "94920"
    },
    {
      "Full Name": "Cordova, Braulio Resendiz",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth+",
      "Phone Number": "(415) 235-9527",
      "Email Address": "brauliocordova3@gmail.com",
      "Street 1": "42 Los Ranchitos Road #7",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94903"
    },
    {
      "Full Name": "Helmueller, Jacob",
      "Dues Yr.": "2017",
      "Level": "Non-Member",
      "Y/A": "Youth+",
      "Phone Number": "(415) 612-4259",
      "Email Address": "tykotoms@hotmail.com",
      "Street 1": "760 Arlington Circle",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94947"
    },
    {
      "Full Name": "Kainz, Felix",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth+",
      "Phone Number": "(415) 257-6367",
      "Email Address": "felix.kainz1@gmail.com",
      "Street 1": "27 Glen Ave",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Larsen, Kenneth",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Youth+",
      "Phone Number": "(415) 275-4634",
      "Email Address": "kennyrlarsen@gmail.com",
      "Street 1": "1020 Susan Way",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94947"
    },
    {
      "Full Name": "Moynihan, Dylan G.",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth+",
      "Phone Number": "(415) 300-6684",
      "Email Address": "dylan.moynihan@gmail.com",
      "Street 1": "597 Fairhills Drive",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Ward, Ryan",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Youth+",
      "Phone Number": "(415) 454-6386",
      "Email Address": "r.n.ward@mindspring.com",
      "Street 1": "69 Rafael Drive",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Aguirre, Javier",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 678-9261",
      "Email Address": "javieragguirre122@gmail.com",
      "Street 1": "32 Front St",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Blum, Eli",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 332-7546",
      "Email Address": "eliblum26@gmail.com",
      "Street 1": "800 Spring Street",
      "City": "Sausalito",
      "State": "CA",
      "Zip Code": "94965"
    },
    {
      "Full Name": "Brousseau, Tristan  Louis ",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 383-1556",
      "Email Address": "TLBrou109@gmail.com",
      "Street 1": "109 Evergreen Ave",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Chambers, Connor ",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 454-4002",
      "Email Address": "connorchambers@gmail.com",
      "Street 1": "14 Beverley Way",
      "City": "San Anselmo",
      "State": "CA",
      "Zip Code": "94960"
    },
    {
      "Full Name": "Everage, Grayson T",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 306-4546",
      "Email Address": "grayson.everage@gmail.com",
      "Street 1": "254 Throckmorton Ave",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Farnkopf, Zac",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 755-0147",
      "Email Address": "zaccoonf@gmail.com",
      "Street 1": "146 Calumet Avenue",
      "City": "San Anselmo",
      "State": "CA",
      "Zip Code": "94960"
    },
    {
      "Full Name": "Fehring, Cole",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 300-7161",
      "Email Address": "colefehring@gmail.com",
      "Street 1": "74 Calyspo Shores",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94949"
    },
    {
      "Full Name": "Ferhing, Grant C ",
      "Dues Yr.": "2017",
      "Level": "2017",
      "Y/A": "Youth",
      "Phone Number": "(415) 300-7161",
      "Email Address": "grantferhing@gmail.com",
      "Street 1": "74 Calypso Shores",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94949"
    },
    {
      "Full Name": "Frankel, Elliot",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 383-1597",
      "Email Address": "elliotfrankel@gmail.com",
      "Street 1": "702 Summit Avenue",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Fretz, Michael",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 827-2712",
      "Email Address": "mikefretz@gmail.com",
      "Street 1": "1041A 4th St",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94945"
    },
    {
      "Full Name": "Gilmore, David",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 272-7323",
      "Email Address": "david.gilmore88@gmail.com",
      "Street 1": "88 Surrey Avenue",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Gilmore, Edward",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 272-7323",
      "Email Address": "lisa.gilmore88@gmail.com",
      "Street 1": "88 Surrey Ave",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Gilmore, William",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 272-7323",
      "Email Address": "william.gilmore88@gmail.com",
      "Street 1": "88 Surrey Avenue",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Gundersen, Erik",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 524-8197",
      "Email Address": "provocalist@yahoo.com",
      "Street 1": "210 Alpine St",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Hanson, Adrian",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 898-6474",
      "Email Address": "carole@thorhanson.com",
      "Street 1": "250 Saddle Wood Drive",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94945"
    },
    {
      "Full Name": "Hanson, Bryce",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 898-6474",
      "Email Address": "thetrufflehunterz@gmail.com",
      "Street 1": "250 Saddlewood Dr",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94945"
    },
    {
      "Full Name": "Holzer, Joshua",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 888-3541",
      "Email Address": "holzerjp@gmail.com",
      "Street 1": "26 Eagle Rock Road",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Jensen, Andrew",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 924-9341",
      "Email Address": "kevin.w.jensen@gmail.com",
      "Street 1": "36 Mariner Green Dr.",
      "City": "Corte Madera",
      "State": "CA",
      "Zip Code": "94925"
    },
    {
      "Full Name": "Kuhn, Calum",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 302-1110",
      "Email Address": "calum.kuhn@gmail.com",
      "Street 1": "220 Beach Road",
      "City": "Belvedere",
      "State": "CA",
      "Zip Code": "94920"
    },
    {
      "Full Name": "Losey, Edward",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 867-0073",
      "Email Address": "edwardlosey@gmail.com",
      "Street 1": "15 H Lane",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94945"
    },
    {
      "Full Name": "McGrath, Riggs",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 261-7412",
      "Email Address": "mail.mcgrath@gmail.com",
      "Street 1": "117 Crescent Rd",
      "City": "San Anselmo",
      "State": "CA",
      "Zip Code": "94960"
    },
    {
      "Full Name": "Moynihan, Ryan Q.",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 464-7407",
      "Email Address": "rqmoynihan@gmail.com",
      "Street 1": "597 Fairhills Drive",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Parker, Tanner",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 898-3831",
      "Email Address": "tanmanscout@gmail.com",
      "Street 1": "740 Sutro Ave",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94947"
    },
    {
      "Full Name": "Peterson, Chase ",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 388-2454",
      "Email Address": "cjkpeterson@gmail.com",
      "Street 1": "47 Circle Ave.",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Rozell, Joe (Joey)",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 717-1638",
      "Email Address": "nrozell@yahoo.com",
      "Street 1": "245 Corte Del Cerro",
      "City": "Novato",
      "State": "MS",
      "Zip Code": "94949"
    },
    {
      "Full Name": "Shern, Sam",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Email Address": "13shern13@gmail.com",
      "Street 1": "478 Molino Ave.",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Spence, Tanner Lee",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Phone Number": "(415) 493-6423",
      "Email Address": "cherispence@icloud.com",
      "Street 1": "85 Gazania Ct",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94945"
    },
    {
      "Full Name": "Todebush, William",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Youth",
      "Email Address": "wcrt19@gmail.com",
      "Street 1": "PO Box 154 / 827 Smith Rd.",
      "State": "CA",
      "Zip Code": "94942"
    },
    {
      "Full Name": "Young, Tommy",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Youth",
      "Phone Number": "(415) 435-9391",
      "Email Address": "tdyoung13580@gmail.com",
      "Street 1": "30 Bella Vista",
      "City": "Tiburon",
      "State": "CA",
      "Zip Code": "94920"
    },
    {
      "Full Name": "Bailey-Gates, Beth",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Adult",
      "Phone Number": "(415) 457-4300",
      "Email Address": "bethmbg@gmail.com",
      "Street 1": "97 Gregory Dr.",
      "City": "Fairfax",
      "State": "CA",
      "Zip Code": "94930"
    },
    {
      "Full Name": "Barton, Bill G",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 785-7899",
      "Email Address": "bbarton99@gmail.com",
      "Street 1": "26 College Court",
      "City": "Larkspur",
      "State": "CA",
      "Zip Code": "94939"
    },
    {
      "Full Name": "Barton, Joe J",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 785-7899",
      "Email Address": "joebarton9@gmail.com",
      "Street 1": "26 College Ct",
      "City": "Larkspur",
      "State": "CA",
      "Zip Code": "94939"
    },
    {
      "Full Name": "Bauer, Peter",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Adult",
      "Phone Number": "(415) 453-4391",
      "Email Address": "apbauer@aol.com",
      "Street 1": "114 Misson Ave",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Bode, Fred",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 309-4980",
      "Email Address": "fpbode@comcast.net",
      "Street 1": "200 Center Street",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901-1720"
    },
    {
      "Full Name": "Cardinal, Chris",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 864-2345",
      "Email Address": "Chris@continentalgraphix.com",
      "Street 1": "166 Riviera Drive",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Coronado Sr., Willy",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 368-2680",
      "Email Address": "willycmarin@yahoo.com \n",
      "Street 1": "342 Jean Street",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Del Secco, Robert ",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Adult",
      "Phone Number": "(415) 388-0550",
      "Email Address": "gogaranger@gmail.com",
      "Street 1": "105 Evergreen Ave.",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Dybeck, Michael ",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 454-1081",
      "Email Address": "mdybeck@boyscouts-marin.org",
      "Street 1": "225 West End Ave.",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Farnkopf, Ned",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Adult",
      "Phone Number": "(415) 302-7681",
      "Email Address": "nedbluesky@hotmail.com",
      "Street 1": "122 Calumet Ave.",
      "City": "San Anselmo",
      "State": "CA",
      "Zip Code": "94960"
    },
    {
      "Full Name": "Fretz, Brian",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Adult",
      "Phone Number": "(415) 847-9686",
      "Email Address": "brianfretz@gmail.com",
      "Street 1": "1041A 4th St",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94945"
    },
    {
      "Full Name": "Gilmore, Peter",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Y/A": "Adult",
      "Phone Number": "(415) 370-4591",
      "Email Address": "ebgas@sbcglobal.net",
      "Street 1": "88 Surrey Avenue",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Mei, Tony",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Adult",
      "Phone Number": "(415) 883-4463",
      "Email Address": "tonymei.novato@gmail.com",
      "Street 1": "15 Dolpin Isle",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94949"
    },
    {
      "Full Name": "Moynihan, Kenneth (Kenn)",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 990-0595",
      "Email Address": "kwm597@gmail.com",
      "Street 1": "597 Fairhills Dr.",
      "City": "San Rafael",
      "State": "CA",
      "Zip Code": "94901"
    },
    {
      "Full Name": "Otavka, Mark",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Adult",
      "Phone Number": "(415) 457-0406",
      "Email Address": "mark@markotavka.com",
      "Street 1": "69 Sequoia Road",
      "City": "Fairfax",
      "State": "CA",
      "Zip Code": "94930"
    },
    {
      "Full Name": "Schafer, Austin",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 898-9391",
      "Email Address": "acsmars@gmail.com",
      "Street 1": "896 Sutro Ave",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94947"
    },
    {
      "Full Name": "Schafer, Paul",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 572-4494",
      "Email Address": "schaferdds@yahoo.com",
      "Street 1": "896 Sutro Ave.",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94947"
    },
    {
      "Full Name": "Swalberg, Matthew",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Y/A": "Adult",
      "Phone Number": "(415) 257-8918",
      "Email Address": "matt267@comcast.net",
      "Street 1": "49 Valley Rd.",
      "City": "San Anselmo",
      "State": "CA",
      "Zip Code": "94960"
    },
    {
      "Full Name": "Swalberg, Michael",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 257-8918",
      "Email Address": "mtswalberg@gmail.com",
      "Street 1": "49 Valley Rd",
      "City": "San Anselmo",
      "State": "CA",
      "Zip Code": "94960"
    },
    {
      "Full Name": "Tong , Jeff",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 897-3703",
      "Email Address": "jtong.eagle2@gmail.com",
      "Street 1": "804 Wilson Ave.",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94947"
    },
    {
      "Full Name": "Tong, Bob",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 328-3371",
      "Email Address": "rtong.eagle1@gmail.com",
      "Street 1": "804 Wilson Ave.",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94947"
    },
    {
      "Full Name": "Tong, Mickey",
      "Dues Yr.": "2017",
      "Level": "Vigil",
      "Y/A": "Adult",
      "Phone Number": "(415) 897-3703",
      "Email Address": "mischellt@gmail.com",
      "Street 1": "804 Wilson Ave.",
      "City": "Novato",
      "State": "CA",
      "Zip Code": "94947"
    },
    {
      "Full Name": "Blum, Jacob  Daniel",
      "Dues Yr.": "2017",
      "Level": "Brotherhood",
      "Phone Number": "(415) 332-7546",
      "Email Address": "jacobdanielblum@gmail.com"
    },
    {
      "Full Name": "Blum, Michael",
      "Dues Yr.": "2017",
      "Level": "Non-Member"
    },
    {
      "Full Name": "Fehring, Grant",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Email Address": "grantfehring@gmail.com"
    },
    {
      "Full Name": "Halloran, John",
      "Dues Yr.": "2017",
      "Level": "Ordeal",
      "Phone Number": "(415) 888-8841",
      "Email Address": "j12alloran@gmail.com",
      "Street 1": "171 Elm Ave.",
      "City": "Mill Valley",
      "State": "CA",
      "Zip Code": "94941"
    },
    {
      "Full Name": "Shern, Scott",
      "Dues Yr.": "2017",
      "Level": "Non-Member"
    }
  ]
}
